"""add visibility

Revision ID: dfeabcdae043
Revises: 8b49fa9c2697
Create Date: 2026-09-27 04:20:50.724809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfeabcdae043'
down_revision: Union[str, Sequence[str], None] = '8b49fa9c2697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('visibility', sa.String(length=20), server_default='public', nullable=False))
    op.add_column('reposts', sa.Column('visibility', sa.String(length=20), server_default='public', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reposts', 'visibility')
    op.drop_column('posts', 'visibility')
    # ### end Alembic commands ###
