"""Add comment media and edit delete tracking

Revision ID: ed1939f2a260
Revises: eb2aa9d60dd8
Create Date: 2026-09-22 00:57:55.275446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed1939f2a260'
down_revision: Union[str, Sequence[str], None] = 'eb2aa9d60dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('comments', sa.Column('is_edited', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_deleted')
    op.drop_column('comments', 'is_edited')
    op.drop_column('comments', 'image_url')
    # ### end Alembic commands ###
