"""add quotes

Revision ID: f0a27fb1c3f2
Revises: 73032fd71a28
Create Date: 2026-09-21 01:22:18.380967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a27fb1c3f2'
down_revision: Union[str, Sequence[str], None] = '73032fd71a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('quoted_post_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_posts_quoted_post_id'), 'posts', ['quoted_post_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'posts', ['quoted_post_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_quoted_post_id'), table_name='posts')
    op.drop_column('posts', 'quoted_post_id')
    # ### end Alembic commands ###
